### ISSUE TITLE
TC kimlik Placeholder

### ISSUE THREAD

**Issue by halimkilic** [intensesoftware/hezarfen-for-woocommerce#1]
T.C kimlik alanında placeholder olmadığı için ne yazılacağı belli değil. 

Ödeme formundaki alanlar otomatik olarak sıralansın mı? özelliği aktif edildiğinde Bireysel alanının altına bir alan açılıyor. Bu alanda gözükmüyor.

https://hizliresim.com/4eOFTF

**Comment by mskapusuz** [comment]
Merhaba Halim Bey,

Bildirimiz için teşekkürler.

Yalnızca input label desteği bulunuyordu. 1.3.1 versiyonumuzla, T.C. no, vergi dairesi ve vergi no alanları için placeholder desteği eklenmiştir.

Selamlar
