### ISSUE TITLE
Ödeme sayfasında vergi alanları gösterimi

### ISSUE THREAD

**Issue by HamdiKapusuz** [intensesoftware/hezarfen-for-woocommerce#10]
- Ödeme sayfasında vergi alanları gösterilsin mi? Seçeneğini pasif ettiğimde ödeme sayfasında boş kutucuklar çıkıyor. Fakat "Ödeme formundaki alanlar otomatik olarak sıralansın mı?" seçeceğini pasif ettiğimde ödeme sayfası normale dönüyor.
<img width="738" alt="Ekran Resmi 2022-01-21 10 28 53" src="https://user-images.githubusercontent.com/77005926/150484921-3e4bfdec-a3b3-4000-8c1b-addb0eecb1be.png">
<img width="698" alt="Ekran Resmi 2022-01-21 10 33 24" src="https://user-images.githubusercontent.com/77005926/150485354-2c3ccde1-6c91-4646-b534-0ff8361c9333.png">

**Comment by mskapusuz** [comment]
@HamdiKapusuz bey, https://github.com/intensesoftware/hezarfen-for-woocommerce/issues/22 ile aynı sorun değil mi? v1.4.5 ile çözüldü.
