### ISSUE TITLE
Incompatible extensions for HPOS (High-Performance Order Storage)

### ISSUE THREAD

**Issue by onurkorunlu** [intensesoftware/hezarfen-for-woocommerce#102]
https://woo.com/document/high-performance-order-storage

Can any improvements be made for compatibility?

**Comment by mskapusuz** [comment]
@mucahidbal bey could you please continue with this task (for both of the lite and Pro versions)

**Comment by mskapusuz** [comment]
@mucahidbal thanks for the update
