### ISSUE TITLE
İlçe ve Mahalleyi Tekrar Seçmek Gerekiyor

### ISSUE THREAD

**Issue by istisna** [intensesoftware/hezarfen-for-woocommerce#2]
Kayıtlı kullanıcı olarak sepette ilçe ve mahalle adresi görüntüleniyor. Ödeme aşamasında bu bilgileri tekrar seçmek durumunda kalıyoruz. Beklentim tekrar seçmeden otomatik seçili gelmesi olurdu.

Bakınız sepette adresimi görüyorum. Yani sistem ilçe ve mahalleyi biliyor:

![Screen Shot 2021-04-17 at 15 20 42](https://user-images.githubusercontent.com/19158533/115113085-21bc6080-9f91-11eb-9499-bcb3ab81a0f9.png)

Burada yeniden istiyor benden bilgileri. Kendisi sorgulasın bulsun. Bulamaz mı? Olamaz mı : )

![Screen Shot 2021-04-17 at 15 20 57](https://user-images.githubusercontent.com/19158533/115113083-2123ca00-9f91-11eb-94ee-c2cdc74e3432.png)

**Comment by istisna** [comment]
@mskapusuz dün yine gündem oldu bu problem : ) Yememiş içmemiş aramış yahu bir müşteri : ))) mahalle seçip duruyorum daha mı öğrenemedi sistem diye : )))

**Comment by HamdiKapusuz** [comment]
Merhaba,

Problem Ver. 1.4.0 itibariyle giderilmiştir.
