### ISSUE TITLE
select2 initialize edilirken 100% width yapilmasi

### ISSUE THREAD

**Issue by mskapusuz** [intensesoftware/hezarfen-for-woocommerce#25]
Odeme ekraninda (https://github.com/intensesoftware/hezarfen-for-woocommerce/blob/master/assets/js/checkout.js) select2 initialize edilirken `width: '100%'` config bilgisini de eklemeliyiz, aksi halde bazi temalarda il, ilce gibi select2 alanlari tam genislik gorunmuyor.

**Comment by mskapusuz** [comment]
@mucahidbal bey, desteginizi rica ederim.

**Comment by mucahidbal** [comment]
@mskapusuz bey bu sorunu PR#19'da çözmüştüm. Merge edildiğinde bu sorun çözülecektir.
