### ISSUE TITLE
Mahalle alanı alfabetik sıralama

### ISSUE THREAD

**Issue by mskapusuz** [intensesoftware/hezarfen-for-woocommerce#35]
https://wordpress.org/support/topic/mahalle-alani-alfabetik-siralama/ tarafından raporlandı.

**Comment by mucahidbal** [comment]
@mskapusuz bey bu sorunu iki şekilde çözebilirim:
- Ajax sonucu dönerken array'i sort yaparak
- Tüm mahalle veri dosyalarını alfabetik olarak sıralayarak

Biliyorsunuz ilk yöntemi uygulamak çok basit fakat birazcık performans düşüşü olur, ikinci yöntemi uygulamak zaman alır fakat performans düşüşü olmaz.

Nasıl yapalım?

**Comment by mskapusuz** [comment]
@mucahidbal bey, ikinci yöntemle ilerleyelim lütfen. Mahalle ID'lerinde bir bozulma olmaması yeterli. Teşekkürler.
