### ISSUE TITLE
Ödeme ekranında ilçe alanına gelindiğinde klavye tuşlarıyla yazılabilmesi

### ISSUE THREAD

**Issue by mskapusuz** [intensesoftware/hezarfen-for-woocommerce#40]
Ödeme ekranında, ülke alanı seçildiğinde, select2 içerisindeki text field seçilmesine gerek kalmadan klavye ile veri yazılabiliyor.

Ancak il, ilçe ve mahalle alanlarında içerideki text input'a tıklanması gerekiyor. Ayrıca tab ile geçiş yapıldığında da aynı sorun yaşanıyor, bu erişilebilirlik sorununu gidermeliyiz.

**Comment by mucahidbal** [comment]
@mskapusuz bey Chrome ve Firefox'ta denedim herhangi bir problemle karşılaşmadım. Acaba sorun Safari ile mi ilgili?

**Comment by mskapusuz** [comment]
> @mskapusuz bey Chrome ve Firefox'ta denedim herhangi bir problemle karşılaşmadım. Acaba sorun Safari ile mi ilgili?

@mucahidbal bey incelemeniz için teşekkürler. Şimdi tekrar kontrol ettim, master branch head committe sorun görünmüyor, sanırım epey eskiden sorun vardı, son commitleri çekip denediğimde bahsettiğim problem gitti. Konuyu kapatıyorum. 👍
