### ISSUE TITLE
PHP 8 Hataları

### ISSUE THREAD

**Issue by HamdiKapusuz** [intensesoftware/hezarfen-for-woocommerce#44]
![Ekran Resmi 2022-09-16 16 22 52](https://user-images.githubusercontent.com/77005926/190648934-5164fd1c-4b59-4831-a62f-149e4417dbfc.png)

**Comment by mucahidbal** [comment]
@HamdiKapusuz bey bu hatayı aldığınız TC Kimlik No'yu paylaşabilir misiniz?

**Comment by HamdiKapusuz** [comment]
> @HamdiKapusuz bey bu hatayı aldığınız TC Kimlik No'yu paylaşabilir misiniz?

Şuan hatırlamıyorum ama 11111111111 dir sanırım
