### ISSUE TITLE
Hezarfen 1.5.0 Hesabım Sayfası Feedback

### ISSUE THREAD

**Issue by HamdiKapusuz** [intensesoftware/hezarfen-for-woocommerce#59]
“Ödeme formundaki alanlar otomatik olarak sıralansın mı?” seçeneği ile ödeme kısmında en önce ülke seçimini türkiye seçtirebiliyoruz fakat bu özellik hesabım kısmında çalışmadığı için ülke seçimi alt kısımlarda bir yerlerde kalıyor. Ülke seçmeyince en başta il seçiliyor sonra ilçeler gelmiyor. Tabiki aynı olay “Posta kodu alanları gizlensin mi?” özelliği için de geçerli. En son olarak çok da önemli olmayan bir şey Türkiye dışındaki bir ülkeyi seçtiğimizde il kısmı sanki bir seçenek seçilecek gibi olup “Bir seçenek belirleyin” şeklinde bir placeholder ile karşımıza çıkıyor.

Feedback: https://wordpress.org/support/topic/hesabim-sayfasi-feedback/

Başka bir müşteri dönüşü:

Merhabalar güncellemeden sonra hezarfen eklentesi otomatik eskişehir ili seçili olarak geliyor.
müşterilerim ili değğiştirdiğinde ilçeler hala eskişehir olarak kalıyor. daha önceden böyle bir sıkıntı yaşamaştık
çözmüştünüz. şuanda yine aynısı oldu. yardımcı olursanız sevinirim. 
****** web sitemizden test edebilirsinz.

Link: https://my.livechatinc.com/tickets/WBOWN

**Comment by mucahidbal** [comment]
> Merhabalar güncellemeden sonra hezarfen eklentesi otomatik eskişehir ili seçili olarak geliyor.
müşterilerim ili değğiştirdiğinde ilçeler hala eskişehir olarak kalıyor. daha önceden böyle bir sıkıntı yaşamaştık
çözmüştünüz. şuanda yine aynısı oldu. yardımcı olursanız sevinirim.

@HamdiKapusuz bey eğer bu müşteri mahalle bazlı gönderim eklentisini kullanıyorsa şu PR'daki versiyonu müşteriye gönderebilir misiniz:
https://github.com/intensesoftware/mahalle-bazli-gonderim-bedeli-for-hezarfen/pull/31

**Comment by HamdiKapusuz** [comment]
> > Merhabalar güncellemeden sonra hezarfen eklentesi otomatik eskişehir ili seçili olarak geliyor.
> > müşterilerim ili değğiştirdiğinde ilçeler hala eskişehir olarak kalıyor. daha önceden böyle bir sıkıntı yaşamaştık
> > çözmüştünüz. şuanda yine aynısı oldu. yardımcı olursanız sevinirim.
> 
> @HamdiKapusuz bey eğer bu müşteri mahalle bazlı gönderim eklentisini kullanıyorsa şu PR'daki versiyonu müşteriye gönderebilir misiniz: [intensesoftware/mahalle-bazli-gonderim-bedeli-for-hezarfen#31](https://github.com/intensesoftware/mahalle-bazli-gonderim-bedeli-for-hezarfen/pull/31)

Merhaba mahalle bazlı gönderim eklentisi kullanmıyor.

**Comment by mucahidbal** [comment]
> Merhabalar güncellemeden sonra hezarfen eklentesi otomatik eskişehir ili seçili olarak geliyor. müşterilerim ili değğiştirdiğinde ilçeler hala eskişehir olarak kalıyor. daha önceden böyle bir sıkıntı yaşamaştık çözmüştünüz. şuanda yine aynısı oldu. yardımcı olursanız sevinirim. ****** web sitemizden test edebilirsinz.
> 
> Link: https://my.livechatinc.com/tickets/WBOWN

@HamdiKapusuz @mskapusuz merhabalar.

livechatinc.com paneline giriş yapamıyorum, subscription ended diyor.

Eskişehir ilinin otomatik olarak seçili gelmesi Hezarfen eklentisiyle ilgili bir durum değil, **Woocommerce > Ayarlar > Genel > Varsayılan müşteri konumu** ayarını Eskişehir olarak ayarlamışlardır. Onu **varsayılan konum yok** olarak ayarlarlarsa otomatik olarak Eskişehir seçili gelmez. İsterseniz bunu müşteriye iletebilirsiniz.

İlçelerin hala Eskişehir ilçeleri olması sorununu sitenin bir kopyasını alarak, veya geçici olarak Hezarfen eklentisini aktif etmelerini rica ederek kontrol edebilirim.

**Comment by mucahidbal** [comment]
> En son olarak çok da önemli olmayan bir şey Türkiye dışındaki bir ülkeyi seçtiğimizde il kısmı sanki bir seçenek seçilecek gibi olup “Bir seçenek belirleyin” şeklinde bir placeholder ile karşımıza çıkıyor.

@HamdiKapusuz bey bu sorun Hezarfen eklentisiyle ilgili değil, müşteri Hezarfen eklentisini devre dışı bırakarak test edebilir, ben test ettim. Woocommerce ile ilgili bir sorun.
