### ISSUE TITLE
Deprecated JQuery Query.fn.change()

### ISSUE THREAD

**Issue by mskapusuz** [intensesoftware/hezarfen-for-woocommerce#70]
Deprecated olan metodu, güncel metod ile değiştirmeliyiz.

https://wordpress.org/support/topic/mahalle-secilememe/

**Comment by mskapusuz** [comment]
@mucahidbal bey, musteri tarafindan belirtilen mahalle secilememesi sorunu icin de testler yapabilir misiniz, eger sorun tespit ederseniz onu da gideririz.

**Comment by mucahidbal** [comment]
@mskapusuz bey müşterinin web sitesini biliyor musunuz?
